name: Java CI with Gradle

on:
  push:
    branches: [ "server" ]

permissions:
  contents: read

env:
  S3_BUCKET_NAME: jbawsbucket1

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      #      - uses: actions/checkout@v3
      #      - run : touch ./server/src/main/resources/application.yml
      #      - run : echo "${{secrets.BE_APPLICATION}}" > ./server/src/main/resources/application.yml

      - name : Add permission
        run : chmod +x ./server/gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
          # Path to the root directory of the build
          build-root-directory: ./server
          # Path to the Gradle executable
          gradle-executable: ./server