
on:
  push:
    branches: [ "server" ]

permissions:
  contents: read

env:
  S3_BUCKET_NAME: jbawsbucket1

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Run chmod to make gradlew executable
        run: chmod +x ./server/gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
          build-root-directory : ./server
          gradle-executabae : ./server
